# .github/workflows/check-now.yml
name: Check Dependencies Now

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit --strict
